"""
PSPP Syntax Generator

Generates PSPP syntax for recoding and cross-tabulation.

Supported transformation types:
- range_grouping: RECODE with THRU ranges
- category_consolidation: RECODE with value lists
- derived: COMPUTE with formula
- top_bottom_box: RECODE for top/bottom box scoring

Example:
    >>> gen = RecodingSyntaxGenerator()
    >>> syntax = gen.generate_rule(recoding_rule)
    >>> print(syntax)
    RECODE age (0 THRU 30 = 1) (31 THRU 50 = 2) INTO age_group.
"""

import logging
from typing import Dict, Any, List, Optional
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class RecodingRule:
    """
    Represents a single recoding rule.

    Attributes:
        source_variable: Source variable name
        target_variable: Target variable name
        transformation_type: One of: range_grouping, category_consolidation, derived, top_bottom_box
        description: Human-readable description
        rules: List of rule mappings (varies by type)
    """
    source_variable: str
    target_variable: str
    transformation_type: str
    description: str
    rules: List[Dict[str, Any]]

    def validate(self) -> tuple[bool, Optional[str]]:
        """Validate the rule structure."""
        valid_types = {
            "range_grouping",
            "category_consolidation",
            "derived",
            "top_bottom_box",
        }

        if self.transformation_type not in valid_types:
            return False, f"Invalid transformation_type: {self.transformation_type}"

        if not self.rules:
            return False, "Rules list is empty"

        return True, None


class RecodingSyntaxGenerator:
    """
    Generate PSPP RECODE syntax from recoding rules.

    Example:
        >>> gen = RecodingSyntaxGenerator()
        >>> syntax = gen.generate_syntax([rule1, rule2])
        >>> print(syntax)
    """

    def __init__(
        self,
        metadata_lookup: Optional[Dict[str, Dict[str, Any]]] = None,
    ):
        """
        Initialize the generator.

        Args:
            metadata_lookup: Optional dict mapping variable names to metadata
        """
        self.metadata_lookup = metadata_lookup or {}

    def generate_syntax(
        self,
        recoding_rules: List[Dict[str, Any]],
        file_label: Optional[str] = None,
    ) -> str:
        """
        Generate PSPP recoding syntax from a list of rules.

        Args:
            recoding_rules: List of recoding rule dictionaries
            file_label: Optional description for the syntax file

        Returns:
            Complete PSPP syntax as string

        Example:
            >>> gen = RecodingSyntaxGenerator()
            >>> rules = [{
            ...     "source_variable": "age",
            ...     "target_variable": "age_group",
            ...     "transformation_type": "range_grouping",
            ...     "rules": [...]
            ... }]
            >>> syntax = gen.generate_syntax(rules)
        """
        lines = []

        # Header
        lines.extend(self._generate_header(file_label))

        # Generate each rule
        for idx, rule_dict in enumerate(recoding_rules, 1):
            rule = RecodingRule(
                source_variable=rule_dict.get("source_variable", ""),
                target_variable=rule_dict.get("target_variable", ""),
                transformation_type=rule_dict.get("transformation_type", ""),
                description=rule_dict.get("description", ""),
                rules=rule_dict.get("rules", []),
            )

            # Validate
            is_valid, error = rule.validate()
            if not is_valid:
                logger.warning(f"Skipping invalid rule {idx}: {error}")
                continue

            # Generate syntax
            rule_syntax = self._generate_rule(rule, idx)
            lines.extend(rule_syntax)

        # Footer
        lines.append("")
        lines.append("* Execute Recoding")
        lines.append("EXECUTE.")

        return "\n".join(lines)

    def _generate_header(
        self,
        file_label: Optional[str] = None,
    ) -> List[str]:
        """Generate header comments."""
        from datetime import datetime

        lines = []
        lines.append("* Recoding Rules Generated by SPSS Analyzer")
        lines.append(f"* Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        if file_label:
            lines.append(f"* {file_label}")
        lines.append("*")
        lines.append("")
        return lines

    def _generate_rule(
        self,
        rule: RecodingRule,
        index: int,
    ) -> List[str]:
        """Generate syntax for a single rule."""
        lines = []

        source_var = rule.source_variable
        target_var = rule.target_variable
        transform_type = rule.transformation_type

        lines.append(f"* Rule {index}: {source_var} → {target_var}")
        if rule.description:
            lines.append(f"* {rule.description}")

        # Generate transformation-specific syntax
        if transform_type == "range_grouping":
            lines.extend(self._generate_range_grouping(rule))
        elif transform_type == "category_consolidation":
            lines.extend(self._generate_category_consolidation(rule))
        elif transform_type == "derived":
            lines.extend(self._generate_derived(rule))
        elif transform_type == "top_bottom_box":
            lines.extend(self._generate_top_bottom_box(rule))
        else:
            logger.warning(f"Unknown transformation type: {transform_type}")

        lines.append("")
        return lines

    def _generate_range_grouping(
        self,
        rule: RecodingRule,
    ) -> List[str]:
        """
        Generate RECODE syntax for range grouping.

        Example:
            RECODE income (0 THRU 30000 = 1) (30001 THRU 60000 = 2)
                      (60001 THRU HI = 3)
                INTO income_recoded.
        """
        lines = []
        source_var = rule.source_variable
        target_var = rule.target_variable
        rules = rule.rules

        recode_parts = []

        for r in rules:
            source_min = r.get("source_min")
            source_max = r.get("source_max")
            target_value = r.get("target_value")

            if source_min is None or source_max is None or target_value is None:
                continue

            # Handle HI keyword
            if str(source_max).upper() == "HI" or source_max == "HI":
                range_spec = f"{source_min} THRU HI"
            else:
                range_spec = f"{source_min} THRU {source_max}"

            recode_parts.append(f"({range_spec} = {target_value})")

        if not recode_parts:
            logger.warning(f"No valid ranges for {source_var}")
            return []

        # Build RECODE line
        recode_line = f"RECODE {source_var} "
        recode_line += " ".join(recode_parts)
        recode_line += f"\n    INTO {target_var}."
        lines.append(recode_line)

        # Add labels
        lines.extend(self._generate_labels(rule))

        return lines

    def _generate_category_consolidation(
        self,
        rule: RecodingRule,
    ) -> List[str]:
        """
        Generate RECODE syntax for category consolidation.

        Example:
            RECODE occupation ('Farmer'='Agriculture') ('Fisherman'='Agriculture')
                INTO occupation_recoded.
        """
        lines = []
        source_var = rule.source_variable
        target_var = rule.target_variable
        rules = rule.rules

        # Get source variable type
        source_metadata = self.metadata_lookup.get(source_var, {})
        source_type = source_metadata.get("variable_type", "numeric")

        recode_parts = []

        for r in rules:
            source_values = r.get("source_values", [])
            target_value = r.get("target_value")

            if not source_values or target_value is None:
                continue

            # Format based on type
            if source_type == "string":
                formatted = [f"'{v}'" for v in source_values]
            else:
                formatted = [str(v) for v in source_values]

            source_spec = ", ".join(formatted)
            recode_parts.append(f"({source_spec} = {target_value})")

        if not recode_parts:
            logger.warning(f"No valid mappings for {source_var}")
            return []

        # Build RECODE line
        recode_line = f"RECODE {source_var} "
        recode_line += " ".join(recode_parts)
        recode_line += f"\n    INTO {target_var}."

        # For string targets, declare STRING type
        if source_type == "string":
            lines.insert(0, f"STRING {target_var} (A50).")

        lines.append(recode_line)
        lines.extend(self._generate_labels(rule))

        return lines

    def _generate_derived(
        self,
        rule: RecodingRule,
    ) -> List[str]:
        """
        Generate COMPUTE syntax for derived variables.

        Example:
            COMPUTE satisfaction_index = MEAN(sat_q1, sat_q2, sat_q3).
        """
        lines = []
        target_var = rule.target_variable
        formula = rule.get("formula", "")

        if not formula:
            logger.warning(f"Derived variable {target_var} missing formula")
            return []

        lines.append(f"COMPUTE {target_var} = {formula}.")
        lines.extend(self._generate_labels(rule))

        return lines

    def _generate_top_bottom_box(
        self,
        rule: RecodingRule,
    ) -> List[str]:
        """
        Generate RECODE syntax for top/bottom box scoring.

        Example:
            RECODE satisfaction (1,2 = 1) (3 = SYSMIS) (4,5 = 0)
                INTO satisfaction_topbox.
        """
        lines = []
        source_var = rule.source_variable
        target_var = rule.target_variable
        rules = rule.rules

        recode_parts = []

        for r in rules:
            source_values = r.get("source_values", [])
            target_value = r.get("target_value")

            if not source_values or target_value is None:
                continue

            formatted = [str(v) for v in source_values]
            source_spec = ", ".join(formatted)
            recode_parts.append(f"({source_spec} = {target_value})")

        if not recode_parts:
            logger.warning(f"No valid mappings for {source_var}")
            return []

        recode_line = f"RECODE {source_var} "
        recode_line += " ".join(recode_parts)
        recode_line += f"\n    INTO {target_var}."

        lines.append(recode_line)
        lines.extend(self._generate_labels(rule))

        return lines

    def _generate_labels(self, rule: RecodingRule) -> List[str]:
        """Generate VARIABLE LABELS and VALUE LABELS commands."""
        lines = []

        # VARIABLE LABELS
        label = rule.description if rule.description else rule.target_variable.replace("_", " ").title()
        lines.append(f"VARIABLE LABELS {rule.target_variable} '{label}'.")

        # VALUE LABELS
        if rule.rules:
            value_labels = []
            for r in rule.rules:
                target_value = r.get("target_value")
                target_label = r.get("target_label", "")
                if target_value is not None and target_label:
                    value_labels.append(f"    {target_value} '{target_label}'")

            if value_labels:
                lines.append(f"VALUE LABELS {rule.target_variable}")
                lines.extend(value_labels)
                lines[-1] += "."

        return lines


class CTablesSyntaxGenerator:
    """
    Generate PSPP CTABLES syntax for cross-tabulation.

    Example:
        >>> gen = CTablesSyntaxGenerator()
        >>> syntax = gen.generate_ctables(table_spec)
        >>> print(syntax)
    """

    STATISTICS_MAP = {
        "count": "count('n')",
        "rowpct": "rowpct('Row %')",
        "columnpct": "columnpct('Column %')",
        "totalpct": "totalpct('Total %')",
        "chisq": "chisq('chi-square')",
        "cramersv": "cramersv('Cramer''s V')",
    }

    def __init__(
        self,
        variable_labels: Optional[Dict[str, str]] = None,
    ):
        """
        Initialize the generator.

        Args:
            variable_labels: Optional dict mapping variable names to labels
        """
        self.variable_labels = variable_labels or {}

    def generate_syntax(
        self,
        table_specifications: List[Dict[str, Any]],
    ) -> str:
        """
        Generate PSPP CTABLES syntax from table specifications.

        Args:
            table_specifications: List of table spec dictionaries

        Returns:
            Complete PSPP syntax as string

        Example:
            >>> gen = CTablesSyntaxGenerator()
            >>> tables = [{
            ...     "table_id": "gender_x_satisfaction",
            ...     "row_variable": "gender",
            ...     "column_variable": "satisfaction",
            ...     "statistics": ["count", "columnpct", "chisq", "cramersv"]
            ... }]
            >>> syntax = gen.generate_syntax(tables)
        """
        lines = []

        # Header
        lines.extend(self._generate_header())

        # Generate each table
        for idx, table_spec in enumerate(table_specifications, 1):
            table_syntax = self._generate_ctable(table_spec, idx)
            lines.extend(table_syntax)

        # Footer
        lines.append("")
        lines.append("* Execute CTABLES")
        lines.append("EXECUTE.")

        return "\n".join(lines)

    def _generate_header(self) -> List[str]:
        """Generate header comments."""
        from datetime import datetime

        lines = []
        lines.append("* Cross-Tabulation Tables Generated by SPSS Analyzer")
        lines.append(f"* Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("*")
        lines.append("")
        lines.append("* Set decimal display format for tables")
        lines.append("SET DECIMAL = TAB.")
        lines.append("")
        return lines

    def _generate_ctable(
        self,
        table_spec: Dict[str, Any],
        index: int,
    ) -> List[str]:
        """Generate CTABLES command for a single table."""
        lines = []

        table_id = table_spec.get("table_id", f"table_{index}")
        row_var = table_spec.get("row_variable", "")
        col_var = table_spec.get("column_variable", "")
        statistics = table_spec.get("statistics", ["count", "columnpct"])
        weight_var = table_spec.get("weight_variable")

        if not row_var or not col_var:
            logger.error(f"Table {table_id} missing row_variable or column_variable")
            return []

        lines.append(f"* Table {index}: {table_id}")
        lines.append("CTABLES")

        # VLABELS
        lines.append(f"    /VLABELS VARIABLES={row_var} {col_var} DISPLAY=DEFAULT")

        # TABLE
        lines.append(f"    /TABLE {row_var} BY {col_var}")

        # WEIGHT
        if weight_var:
            lines.append(f"    /WEIGHT {weight_var}")

        # STATISTICS
        stats_list = []
        for stat in statistics:
            if stat in self.STATISTICS_MAP:
                stats_list.append(self.STATISTICS_MAP[stat])
            else:
                logger.warning(f"Unknown statistic '{stat}' for table {table_id}")

        if stats_list:
            stats_str = " ".join(stats_list)
            lines.append(f"    /STATISTICS {stats_str}.")

        # Add blank line
        lines.append("")

        return lines
