"""
Table Specification Schema

Defines the consolidated table specification structure that combines:
- Indicator definitions
- Recoding rules
- Table specifications (column definitions, metrics, grouping rules)
- Output settings

This is a unified artifact generated by AI (via skills) and consumed by
the library modules for computation.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Union, Literal
from enum import Enum
from datetime import datetime


# ============================================================================
# Enums
# ============================================================================

class MetricType(str, Enum):
    """Types of metrics for cross-tabulation tables."""
    COUNT = "count"
    ROW_PERCENT = "row_percent"
    COLUMN_PERCENT = "column_percent"
    TOTAL_PERCENT = "total_percent"
    MEAN = "mean"
    MEDIAN = "median"
    STD_DEV = "std_dev"
    MIN = "min"
    MAX = "max"


class AggregationType(str, Enum):
    """Types of aggregation for indicator computation."""
    MEAN = "mean"
    SUM = "sum"
    COUNT = "count"
    MEDIAN = "median"
    MODE = "mode"
    WEIGHTED_MEAN = "weighted_mean"


class RecodingType(str, Enum):
    """Types of variable recoding."""
    VALUE_MAP = "value_map"  # Direct value-to-value mapping
    RANGE_MAP = "range_map"  # Range-based mapping
    CONDITION = "condition"  # Conditional expressions


class TableType(str, Enum):
    """Types of tables to generate."""
    CROSSTAB = "crosstab"  # Cross-tabulation (row by column)
    FREQUENCY = "frequency"  # Single variable frequency table
    SUMMARY = "summary"  # Summary statistics (mean, median, etc.)


class VariableSource(str, Enum):
    """Source of variable definition."""
    RAW = "raw"  # Original variable from .sav file
    RECODED = "recoded"  # Recoded variable
    INDICATOR = "indicator"  # Computed indicator


# ============================================================================
# Recoding Rules
# ============================================================================

@dataclass
class ValueMapping:
    """Direct value-to-value mapping."""
    original: Union[str, int, float]
    recoded: Union[str, int, float]


@dataclass
class RangeMapping:
    """Range-based mapping (inclusive ranges)."""
    min_value: Optional[Union[int, float]] = None
    max_value: Optional[Union[int, float]] = None
    recoded_value: Union[str, int, float] = ""
    inclusive: bool = True


@dataclass
class RecodingRule:
    """
    Defines how to recode a variable.

    Examples:
        Value mapping: {1: "Strongly Agree", 2: "Agree", 3: "Neutral"}
        Range mapping: age <= 30 -> "Young", 31-50 -> "Middle", 51+ -> "Senior"
    """
    variable: str  # Source variable name
    new_variable: Optional[str] = None  # Output variable name (if different)
    type: RecodingType = RecodingType.VALUE_MAP
    label: Optional[str] = None  # Variable label

    # For VALUE_MAP type
    value_mappings: Dict[Union[str, int, float], Union[str, int, float]] = field(default_factory=dict)

    # For RANGE_MAP type
    range_mappings: List[RangeMapping] = field(default_factory=list)

    # For CONDITION type
    conditions: List[str] = field(default_factory=list)  # PSPP-style conditions
    condition_values: List[Union[str, int, float]] = field(default_factory=list)

    # Value labels for recoded values
    value_labels: Dict[Union[str, int, float], str] = field(default_factory=dict)

    # Validation
    missing_values: List[Union[str, int, float]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "variable": self.variable,
            "new_variable": self.new_variable,
            "type": self.type.value,
            "label": self.label,
            "value_mappings": self.value_mappings,
            "range_mappings": [
                {
                    "min_value": r.min_value,
                    "max_value": r.max_value,
                    "recoded_value": r.recoded_value,
                    "inclusive": r.inclusive
                }
                for r in self.range_mappings
            ],
            "conditions": self.conditions,
            "condition_values": self.condition_values,
            "value_labels": self.value_labels,
            "missing_values": self.missing_values,
        }


# ============================================================================
# Indicators
# ============================================================================

@dataclass
class VariableRef:
    """Reference to a variable with optional recoding."""
    name: str  # Variable name
    source: VariableSource = VariableSource.RAW
    recoded_as: Optional[str] = None  # If using a recoded version
    weight: float = 1.0  # Weight for aggregation


@dataclass
class Indicator:
    """
    Defines an indicator computed from multiple variables.

    Examples:
        - Customer Satisfaction: mean of q1, q2, q3 (recoded 1-5 to 0-100)
        - Brand Awareness: count of awareness mentions across q10-q15
    """
    id: str  # Unique identifier (e.g., "ind_001")
    name: str  # Human-readable name
    description: Optional[str] = None

    # Variables that make up this indicator
    variables: List[VariableRef] = field(default_factory=list)

    # Aggregation method
    aggregation: AggregationType = AggregationType.MEAN

    # Recoding applied before aggregation
    recoding: Optional[RecodingRule] = None

    # Value labels for indicator categories
    value_labels: Dict[Union[str, int, float], str] = field(default_factory=dict)

    # Display settings
    format_string: Optional[str] = None  # e.g., "{:.1f}", "{:.0%}"
    reverse_coded: bool = False  # If true, reverse the scale

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "variables": [
                {
                    "name": v.name,
                    "source": v.source.value,
                    "recoded_as": v.recoded_as,
                    "weight": v.weight
                }
                for v in self.variables
            ],
            "aggregation": self.aggregation.value,
            "recoding": self.recoding.to_dict() if self.recoding else None,
            "value_labels": self.value_labels,
            "format_string": self.format_string,
            "reverse_coded": self.reverse_coded,
        }


# ============================================================================
# Table Specifications
# ============================================================================

@dataclass
class TableDimension:
    """
    Defines a dimension (row or column) in a cross-tabulation table.

    Can reference:
    - Raw variable
    - Recoded variable
    - Indicator
    """
    variable: str  # Variable name or indicator ID
    source: VariableSource = VariableSource.RAW
    label_override: Optional[str] = None  # Custom label for display
    sort_order: Optional[str] = None  # "asc", "desc", or custom order

    # For categorical variables
    category_order: Optional[List[Union[str, int, float]]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "variable": self.variable,
            "source": self.source.value,
            "label_override": self.label_override,
            "sort_order": self.sort_order,
            "category_order": self.category_order,
        }


@dataclass
class TableMetric:
    """Defines a metric to include in a table."""
    type: MetricType
    label: Optional[str] = None  # Custom label
    decimals: int = 1  # Number of decimal places

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "type": self.type.value,
            "label": self.label,
            "decimals": self.decimals,
        }


@dataclass
class TableSpecification:
    """
    Defines a single cross-tabulation or summary table.

    Examples:
        - "Satisfaction by Gender" (crosstab)
        - "Age Distribution" (frequency)
        - "Customer Satisfaction Summary" (summary)
    """
    id: str  # Unique identifier (e.g., "tab_001")
    title: str  # Table title
    type: TableType = TableType.CROSSTAB

    # Dimensions
    rows: Optional[TableDimension] = None  # Row variable (for crosstab)
    columns: Optional[TableDimension] = None  # Column variable (for crosstab)
    layers: Optional[List[TableDimension]] = None  # Layer variables (multi-way tables)

    # Metrics to compute
    metrics: List[TableMetric] = field(default_factory=lambda: [
        TableMetric(MetricType.COUNT, "n", 0),
        TableMetric(MetricType.ROW_PERCENT, "Row %", 1),
        TableMetric(MetricType.COLUMN_PERCENT, "Column %", 1),
    ])

    # Weight variable
    weight_variable: Optional[str] = None

    # Statistical tests
    include_chi_square: bool = True
    include_cramers_v: bool = True
    significance_level: float = 0.05

    # Display settings
    show_percent_sign: bool = True
    suppress_small_counts: bool = True
    small_count_threshold: int = 5

    # Indicators referenced (if applicable)
    indicator_ids: List[str] = field(default_factory=list)

    # Recoding to apply before generating table
    recodings: List[RecodingRule] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "id": self.id,
            "title": self.title,
            "type": self.type.value,
            "rows": self.rows.to_dict() if self.rows else None,
            "columns": self.columns.to_dict() if self.columns else None,
            "layers": [l.to_dict() for l in self.layers] if self.layers else None,
            "metrics": [m.to_dict() for m in self.metrics],
            "weight_variable": self.weight_variable,
            "include_chi_square": self.include_chi_square,
            "include_cramers_v": self.include_cramers_v,
            "significance_level": self.significance_level,
            "show_percent_sign": self.show_percent_sign,
            "suppress_small_counts": self.suppress_small_counts,
            "small_count_threshold": self.small_count_threshold,
            "indicator_ids": self.indicator_ids,
            "recodings": [r.to_dict() for r in self.recodings],
        }


# ============================================================================
# Output Settings
# ============================================================================

@dataclass
class OutputSettings:
    """Settings for report generation."""
    # Significance filtering
    significance_threshold: float = 0.05
    min_cramers_v: float = 0.1
    min_sample_size: int = 30

    # Output formats
    include_powerpoint: bool = True
    include_html_dashboard: bool = True
    include_csv_export: bool = True

    # PowerPoint settings
    ppt_template: Optional[str] = None
    max_tables_ppt: int = 20  # Only significant tables in PPT

    # HTML dashboard settings
    dashboard_title: str = "Survey Analysis Results"
    include_charts: bool = True
    chart_type: Literal["bar", "column", "heatmap", "mosaic"] = "heatmap"

    # File paths
    output_directory: str = "output"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "significance_threshold": self.significance_threshold,
            "min_cramers_v": self.min_cramers_v,
            "min_sample_size": self.min_sample_size,
            "include_powerpoint": self.include_powerpoint,
            "include_html_dashboard": self.include_html_dashboard,
            "include_csv_export": self.include_csv_export,
            "ppt_template": self.ppt_template,
            "max_tables_ppt": self.max_tables_ppt,
            "dashboard_title": self.dashboard_title,
            "include_charts": self.include_charts,
            "chart_type": self.chart_type,
            "output_directory": self.output_directory,
        }


# ============================================================================
# Main Table Specification
# ============================================================================

@dataclass
class TableSpecificationDocument:
    """
    Root document for the consolidated table specification.

    This is the primary artifact generated by AI (via skills) and consumed
    by the library modules for computation.

    Structure:
        - metadata: Document metadata
        - global_recodings: Recoding rules applied to all tables
        - indicators: Indicator definitions
        - tables: Table specifications
        - output_settings: Output generation settings
    """
    # Document metadata
    version: str = "1.0"
    generated_at: Optional[str] = None  # ISO 8601 timestamp
    source_file: Optional[str] = None  # Original .sav file name

    # Content
    global_recodings: List[RecodingRule] = field(default_factory=list)
    indicators: List[Indicator] = field(default_factory=list)
    tables: List[TableSpecification] = field(default_factory=list)
    output_settings: OutputSettings = field(default_factory=OutputSettings)

    # Free-form notes (for human review)
    notes: Optional[str] = None

    def __post_init__(self):
        """Set generated_at timestamp if not provided."""
        if self.generated_at is None:
            self.generated_at = datetime.utcnow().isoformat() + "Z"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "metadata": {
                "version": self.version,
                "generated_at": self.generated_at,
                "source_file": self.source_file,
            },
            "global_recodings": [r.to_dict() for r in self.global_recodings],
            "indicators": [i.to_dict() for i in self.indicators],
            "tables": [t.to_dict() for t in self.tables],
            "output_settings": self.output_settings.to_dict(),
            "notes": self.notes,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TableSpecificationDocument":
        """Create instance from dictionary (for loading from JSON)."""
        metadata = data.get("metadata", {})
        output_settings_data = data.get("output_settings", {})

        # Parse global recodings
        global_recodings = []
        for r_data in data.get("global_recodings", []):
            recoding = RecodingRule(
                variable=r_data["variable"],
                new_variable=r_data.get("new_variable"),
                type=RecodingType(r_data["type"]),
                label=r_data.get("label"),
                value_mappings=r_data.get("value_mappings", {}),
                range_mappings=[
                    RangeMapping(
                        min_value=r.get("min_value"),
                        max_value=r.get("max_value"),
                        recoded_value=r.get("recoded_value", ""),
                        inclusive=r.get("inclusive", True),
                    )
                    for r in r_data.get("range_mappings", [])
                ],
                conditions=r_data.get("conditions", []),
                condition_values=r_data.get("condition_values", []),
                value_labels=r_data.get("value_labels", {}),
                missing_values=r_data.get("missing_values", []),
            )
            global_recodings.append(recoding)

        # Parse indicators
        indicators = []
        for i_data in data.get("indicators", []):
            variables = [
                VariableRef(
                    name=v["name"],
                    source=VariableSource(v.get("source", "raw")),
                    recoded_as=v.get("recoded_as"),
                    weight=v.get("weight", 1.0),
                )
                for v in i_data.get("variables", [])
            ]
            recoding = None
            if i_data.get("recoding"):
                r_data = i_data["recoding"]
                recoding = RecodingRule(
                    variable=r_data["variable"],
                    new_variable=r_data.get("new_variable"),
                    type=RecodingType(r_data["type"]),
                    label=r_data.get("label"),
                    value_mappings=r_data.get("value_mappings", {}),
                    range_mappings=[
                        RangeMapping(
                            min_value=r.get("min_value"),
                            max_value=r.get("max_value"),
                            recoded_value=r.get("recoded_value", ""),
                            inclusive=r.get("inclusive", True),
                        )
                        for r in r_data.get("range_mappings", [])
                    ],
                    conditions=r_data.get("conditions", []),
                    condition_values=r_data.get("condition_values", []),
                    value_labels=r_data.get("value_labels", {}),
                    missing_values=r_data.get("missing_values", []),
                )

            indicator = Indicator(
                id=i_data["id"],
                name=i_data["name"],
                description=i_data.get("description"),
                variables=variables,
                aggregation=AggregationType(i_data.get("aggregation", "mean")),
                recoding=recoding,
                value_labels=i_data.get("value_labels", {}),
                format_string=i_data.get("format_string"),
                reverse_coded=i_data.get("reverse_coded", False),
            )
            indicators.append(indicator)

        # Parse tables
        tables = []
        for t_data in data.get("tables", []):
            rows = None
            if t_data.get("rows"):
                r_data = t_data["rows"]
                rows = TableDimension(
                    variable=r_data["variable"],
                    source=VariableSource(r_data.get("source", "raw")),
                    label_override=r_data.get("label_override"),
                    sort_order=r_data.get("sort_order"),
                    category_order=r_data.get("category_order"),
                )

            columns = None
            if t_data.get("columns"):
                c_data = t_data["columns"]
                columns = TableDimension(
                    variable=c_data["variable"],
                    source=VariableSource(c_data.get("source", "raw")),
                    label_override=c_data.get("label_override"),
                    sort_order=c_data.get("sort_order"),
                    category_order=c_data.get("category_order"),
                )

            layers = None
            if t_data.get("layers"):
                layers = [
                    TableDimension(
                        variable=l_data["variable"],
                        source=VariableSource(l_data.get("source", "raw")),
                        label_override=l_data.get("label_override"),
                        sort_order=l_data.get("sort_order"),
                        category_order=l_data.get("category_order"),
                    )
                    for l_data in t_data["layers"]
                ]

            metrics = [
                TableMetric(
                    type=MetricType(m["type"]),
                    label=m.get("label"),
                    decimals=m.get("decimals", 1),
                )
                for m in t_data.get("metrics", [])
            ]

            recodings = []
            for r_data in t_data.get("recodings", []):
                recoding = RecodingRule(
                    variable=r_data["variable"],
                    new_variable=r_data.get("new_variable"),
                    type=RecodingType(r_data["type"]),
                    label=r_data.get("label"),
                    value_mappings=r_data.get("value_mappings", {}),
                    range_mappings=[
                        RangeMapping(
                            min_value=r.get("min_value"),
                            max_value=r.get("max_value"),
                            recoded_value=r.get("recoded_value", ""),
                            inclusive=r.get("inclusive", True),
                        )
                        for r in r_data.get("range_mappings", [])
                    ],
                    conditions=r_data.get("conditions", []),
                    condition_values=r_data.get("condition_values", []),
                    value_labels=r_data.get("value_labels", {}),
                    missing_values=r_data.get("missing_values", []),
                )
                recodings.append(recoding)

            table = TableSpecification(
                id=t_data["id"],
                title=t_data["title"],
                type=TableType(t_data.get("type", "crosstab")),
                rows=rows,
                columns=columns,
                layers=layers,
                metrics=metrics,
                weight_variable=t_data.get("weight_variable"),
                include_chi_square=t_data.get("include_chi_square", True),
                include_cramers_v=t_data.get("include_cramers_v", True),
                significance_level=t_data.get("significance_level", 0.05),
                show_percent_sign=t_data.get("show_percent_sign", True),
                suppress_small_counts=t_data.get("suppress_small_counts", True),
                small_count_threshold=t_data.get("small_count_threshold", 5),
                indicator_ids=t_data.get("indicator_ids", []),
                recodings=recodings,
            )
            tables.append(table)

        # Parse output settings
        output_settings = OutputSettings(
            significance_threshold=output_settings_data.get("significance_threshold", 0.05),
            min_cramers_v=output_settings_data.get("min_cramers_v", 0.1),
            min_sample_size=output_settings_data.get("min_sample_size", 30),
            include_powerpoint=output_settings_data.get("include_powerpoint", True),
            include_html_dashboard=output_settings_data.get("include_html_dashboard", True),
            include_csv_export=output_settings_data.get("include_csv_export", True),
            ppt_template=output_settings_data.get("ppt_template"),
            max_tables_ppt=output_settings_data.get("max_tables_ppt", 20),
            dashboard_title=output_settings_data.get("dashboard_title", "Survey Analysis Results"),
            include_charts=output_settings_data.get("include_charts", True),
            chart_type=output_settings_data.get("chart_type", "heatmap"),
            output_directory=output_settings_data.get("output_directory", "output"),
        )

        return cls(
            version=metadata.get("version", "1.0"),
            generated_at=metadata.get("generated_at"),
            source_file=metadata.get("source_file"),
            global_recodings=global_recodings,
            indicators=indicators,
            tables=tables,
            output_settings=output_settings,
            notes=data.get("notes"),
        )


# ============================================================================
# Convenience Functions
# ============================================================================

def create_empty_spec(source_file: Optional[str] = None) -> TableSpecificationDocument:
    """Create an empty table specification document."""
    return TableSpecificationDocument(
        version="1.0",
        source_file=source_file,
    )


def validate_spec_structure(spec: Dict[str, Any]) -> List[str]:
    """
    Perform basic structural validation of a table specification.

    Returns a list of error messages (empty if valid).
    """
    errors = []

    # Check metadata
    if "metadata" not in spec:
        errors.append("Missing 'metadata' section")

    # Check required sections exist
    required_sections = ["tables", "output_settings"]
    for section in required_sections:
        if section not in spec:
            errors.append(f"Missing required section: '{section}'")

    # Validate tables
    tables = spec.get("tables", [])
    if not tables:
        errors.append("No tables defined in specification")

    for i, table in enumerate(tables):
        if "id" not in table:
            errors.append(f"Table {i}: missing 'id'")
        if "title" not in table:
            errors.append(f"Table {i}: missing 'title'")
        if "type" not in table:
            errors.append(f"Table {i}: missing 'type'")

        # For crosstabs, need rows and columns
        if table.get("type") == "crosstab":
            if not table.get("rows") and not table.get("columns"):
                errors.append(f"Table {i} ({table.get('id', 'unknown')}): crosstab requires rows or columns")

    # Validate output settings
    output_settings = spec.get("output_settings", {})
    if "significance_threshold" in output_settings:
        threshold = output_settings["significance_threshold"]
        if not 0 < threshold <= 1:
            errors.append(f"significance_threshold must be between 0 and 1, got {threshold}")

    return errors
