"""
Table Specification Schema

Defines the table specification structure for cross-tabulation analysis.
This matches the table_specification.jsonc format generated by Stage 2 AI.

Structure:
- metadata: Document metadata
- filter_clause: Data filtering rules
- row_indicators: Row indicator specifications
- column_indicators: Column indicator specifications
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Union
from enum import Enum
from datetime import datetime


# ============================================================================
# Enums
# ============================================================================

class VariableSuffix(str, Enum):
    """Suffix types indicating variable transformation."""
    RAW = "_raw"          # Raw SPSS variable, no transformation
    BIN = "_bin"          # Binary (0/1, Yes/No)
    CAT = "_cat"          # Categorical recoded
    T2B = "_t2b"          # Top 2 Box (highest categories)
    B2B = "_b2b"          # Bottom 2 Box (lowest categories)
    NPS = "_nps"          # NPS categorization
    SCA = "_sca"          # Scalar/continuous
    IDX = "_idx"          # Computed index
    Z = "_z"              # Z-score normalized
    PCT = "_pct"          # Percentile rank


class QuestionType(str, Enum):
    """Types of questions in the questionnaire."""
    SINGLE_CHOICE = "Single Choice"
    MULTIPLE_CHOICE = "Multiple Choice"
    MATRIX = "Matrix"
    RATING_SCALE = "Rating Scale"
    NUMERIC_INPUT = "Numeric Input"
    OPEN_ENDED = "Open Ended"


class TabulationType(str, Enum):
    """Types of tabulation statistics."""
    CATEGORICAL = "categorical"
    SCALAR = "scalar"


class MetricType(str, Enum):
    """Types of metrics for tabulation."""
    COLUMN_PERCENT = "column_percent"
    DESCRIPTIVE_STATISTICS = "descriptive_statistics"


# ============================================================================
# Question Reference
# ============================================================================

@dataclass
class QuestionRef:
    """
    Reference to a questionnaire question.

    Attributes:
        code: SPSS variable prefix (Q1, S1, D1)
        label: Short question label
        type: Question type (Single Choice, Multiple Choice, etc.)
    """
    code: str
    label: str
    type: QuestionType

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "code": self.code,
            "label": self.label,
            "type": self.type.value
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "QuestionRef":
        """Create instance from dictionary (for loading from JSON)."""
        return cls(
            code=data["code"],
            label=data["label"],
            type=QuestionType(data["type"])
        )


# ============================================================================
# Base Variable
# ============================================================================

@dataclass
class BaseVariable:
    """
    A single base variable in an indicator.

    Each base variable represents a target variable with its transformation.
    All variables in an indicator typically share the same suffix.

    The generation field uses simplified SPSS-like syntax with only parentheses,
    e.g., "(1 THRU 2=1) (ELSE=0)" - no "RECODE" keyword needed.

    Attributes:
        name: Target variable name (with suffix, e.g., "Q5_SATISFACTION_cat")
        label: Human-readable variable label
        generation: Simplified transformation syntax with parentheses only, null for raw
    """
    name: str = ""
    label: str = ""
    generation: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "name": self.name,
            "label": self.label,
            "generation": self.generation
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "BaseVariable":
        """
        Create instance from dictionary (for loading from JSON).

        Args:
            data: Dictionary containing variable fields
        """
        return cls(
            name=data.get("name", ""),
            label=data.get("label", ""),
            generation=data.get("generation")
        )

    def is_raw(self) -> bool:
        """Check if this is a raw variable (no transformation)."""
        return self.generation is None or self.generation == ""

    def get_suffix(self) -> str:
        """Extract the suffix from the variable name."""
        # Find common suffixes
        for suffix in ["_idx", "_pct", "_z", "_sca", "_nps", "_b2b", "_t2b", "_bin", "_cat", "_raw"]:
            if self.name.endswith(suffix):
                return suffix
        return "_cat"  # Default

    def is_categorical(self) -> bool:
        """Check if this is a categorical variable type."""
        suffix = self.get_suffix()
        return suffix in ["_raw", "_bin", "_cat", "_t2b", "_b2b", "_nps"]

    def is_scalar(self) -> bool:
        """Check if this is a scalar variable type."""
        suffix = self.get_suffix()
        return suffix in ["_sca", "_idx", "_z", "_pct"]


# ============================================================================
# Tabulation Statistics
# ============================================================================

@dataclass
class TabulationStats:
    """
    [LEGACY] Statistics configuration for tabulation.

    NOTE: This class is kept for backward compatibility only.
    New format uses tabulation_type and tabulation_metric directly in IndicatorSpec.

    Attributes:
        type: Type of variable (categorical or scalar)
        metric: Metric to compute (column_percent or descriptive_statistics)
    """
    type: TabulationType
    metric: MetricType

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "type": self.type.value,
            "metric": self.metric.value
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TabulationStats":
        """Create instance from dictionary (for loading from JSON)."""
        return cls(
            type=TabulationType(data["type"]),
            metric=MetricType(data["metric"])
        )


# ============================================================================
# Indicator Specification
# ============================================================================

@dataclass
class IndicatorSpec:
    """
    Defines an indicator for cross-tabulation analysis.

    An indicator can have:
    - A unique indicator code (identifier)
    - A related questionnaire question (code and type)
    - Tabulation type and metric (top-level, parallel with question fields)
    - Three parallel base variable fields: variables, transformations, value_labels

    NOTE: In the new JSON structure, row_indicators and column_indicators are ARRAYS,
    and indicator_code is a field inside each indicator object (parallel with other fields).

    NOTE: Three parallel fields for base variables (at same level, not nested):
        - "base_variables": Dictionary of {variable_name: label}
        - "base_variables_transformations": Dictionary of {variable_name: SPSS_syntax}
        - "base_variables_value_labels": Dictionary of {code: label} (shared value labels)

    Transformation format:
        - Full SPSS RECODE syntax: "RECODE source_var (rules) INTO target_var"
        - Source variable is the original (no suffix like _raw)
        - Example: "RECODE Q5_SAT (1 THRU 2=1) (3=2) (4 THRU 5=3) INTO Q5_SAT_cat"
        - For raw variables: null or omitted

    NOTE: base_variables_value_labels is a DICTIONARY of shared value labels
    (code -> label mapping) that applies to all variables in this indicator.

    Attributes:
        indicator_code: Unique identifier for the indicator
        indicator_label: Human-readable label
        question_code: SPSS variable identifier for the related question
        question_type: Question type (Single Choice, Multiple Choice, Matrix, etc.)
        tabulation_type: Type of variable (categorical or scalar)
        tabulation_metric: Metric to compute (column_percent or descriptive_statistics)
        base_variables: Dictionary of variable names to labels
        base_variables_transformations: Dictionary of variable names to SPSS syntax
        base_variables_value_labels: Dictionary of value codes to labels
    """
    indicator_code: str = ""  # Required field - unique identifier
    indicator_label: str = ""
    question_code: str = ""
    question_type: QuestionType = QuestionType.SINGLE_CHOICE
    tabulation_type: Optional[TabulationType] = None  # Auto-detected if None
    tabulation_metric: Optional[MetricType] = None  # Auto-detected if None
    base_variables: Dict[str, str] = field(default_factory=dict)  # name → label
    base_variables_transformations: Optional[Dict[str, str]] = None  # name → SPSS syntax
    base_variables_value_labels: Optional[Dict[str, str]] = None  # code → label

    def __post_init__(self):
        """Set default tabulation_type and tabulation_metric if not provided."""
        if self.tabulation_type is None or self.tabulation_metric is None:
            # Auto-detect from base_variables
            if self.base_variables:
                first_var_name = next(iter(self.base_variables.keys()))
                # Check suffix to determine type
                if any(first_var_name.endswith(suffix) for suffix in ["_sca", "_idx", "_z", "_pct"]):
                    if self.tabulation_type is None:
                        self.tabulation_type = TabulationType.SCALAR
                    if self.tabulation_metric is None:
                        self.tabulation_metric = MetricType.DESCRIPTIVE_STATISTICS
                else:
                    # Default to categorical for _raw, _bin, _cat, _t2b, _b2b, _nps
                    if self.tabulation_type is None:
                        self.tabulation_type = TabulationType.CATEGORICAL
                    if self.tabulation_metric is None:
                        self.tabulation_metric = MetricType.COLUMN_PERCENT
            else:
                # No base variables - set defaults
                if self.tabulation_type is None:
                    self.tabulation_type = TabulationType.CATEGORICAL
                if self.tabulation_metric is None:
                    self.tabulation_metric = MetricType.COLUMN_PERCENT

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "indicator_code": self.indicator_code,
            "indicator_label": self.indicator_label,
            "question_code": self.question_code,
            "question_type": self.question_type.value if isinstance(self.question_type, QuestionType) else self.question_type,
            "tabulation_type": self.tabulation_type.value if isinstance(self.tabulation_type, TabulationType) else self.tabulation_type,
            "tabulation_metric": self.tabulation_metric.value if isinstance(self.tabulation_metric, MetricType) else self.tabulation_metric,
            "base_variables": self.base_variables,
            "base_variables_transformations": self.base_variables_transformations,
            "base_variables_value_labels": self.base_variables_value_labels,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any], code: str = None) -> "IndicatorSpec":
        """
        Create instance from dictionary (for loading from JSON).

        Args:
            data: Dictionary containing indicator fields
            code: Optional indicator code (when not in data)
        """
        # Support both old format (questionnaire_questions) and new format (question_code, question_type)
        if "question_code" in data:
            # New format
            question_code = data.get("question_code", "")
            question_type = QuestionType(data.get("question_type", "Single Choice"))
        elif "questionnaire_questions" in data and data["questionnaire_questions"]:
            # Old format: extract from first questionnaire question
            first_q = data["questionnaire_questions"][0]
            question_code = first_q.get("code", "")
            question_type = QuestionType(first_q.get("type", "Single Choice"))
        else:
            # Fallback
            question_code = ""
            question_type = QuestionType.SINGLE_CHOICE

        # Handle base_variables - support multiple formats for backward compatibility
        base_vars = data.get("base_variables", {})
        base_vars_transformations = data.get("base_variables_transformations")
        base_vars_value_labels = data.get("base_variables_value_labels")

        # Check if old nested format (with variable_list, generation_rules, unified_values)
        if isinstance(base_vars, dict) and "variable_list" in base_vars:
            # Old nested format - extract and convert to parallel fields
            base_vars = base_vars.get("variable_list", {})
            base_vars_transformations = base_vars.get("generation_rules")
            base_vars_value_labels = base_vars.get("unified_values")
        elif isinstance(base_vars, list):
            # Legacy list format - convert
            new_vars = {}
            new_transforms = {}
            for bv in base_vars:
                name = bv.get("name", "")
                if name:
                    new_vars[name] = bv.get("label", "")
                    gen = bv.get("generation")
                    if gen:
                        new_transforms[name] = gen
            base_vars = new_vars
            base_vars_transformations = new_transforms if new_transforms else None
            # value_labels would be in a separate field
            base_vars_value_labels = data.get("base_variables_values") or data.get("unified_values")

        # Handle tabulation configuration - support both old and new formats
        tabulation_type = None
        tabulation_metric = None

        # New format: tabulation_type and tabulation_metric at top level
        if "tabulation_type" in data:
            tabulation_type = TabulationType(data["tabulation_type"])
        if "tabulation_metric" in data:
            tabulation_metric = MetricType(data["tabulation_metric"])

        # Old format: tabulation_statistics wrapper (for backward compatibility)
        if data.get("tabulation_statistics") and (tabulation_type is None or tabulation_metric is None):
            stats_data = data["tabulation_statistics"]
            if tabulation_type is None and "type" in stats_data:
                tabulation_type = TabulationType(stats_data["type"])
            if tabulation_metric is None and "metric" in stats_data:
                tabulation_metric = MetricType(stats_data["metric"])

        # Support both old and new formats
        ind_code = data.get("indicator_code") or code

        return cls(
            indicator_code=ind_code,
            indicator_label=data.get("indicator_label", ""),
            question_code=question_code,
            question_type=question_type,
            tabulation_type=tabulation_type,
            tabulation_metric=tabulation_metric,
            base_variables=base_vars,
            base_variables_transformations=base_vars_transformations,
            base_variables_value_labels=base_vars_value_labels,
        )

    def get_scenario_type(self) -> str:
        """
        Determine the crosstab scenario type based on configuration.

        Returns:
            Scenario type: cat_single, cat_multi, scalar_single, or scalar_multi
        """
        var_count = len(self.base_variables)

        if self.tabulation_type == TabulationType.CATEGORICAL:
            if var_count == 1:
                return "cat_single"
            else:
                return "cat_multi"
        else:  # SCALAR
            if var_count == 1:
                return "scalar_single"
            else:
                return "scalar_multi"


# ============================================================================
# Main Table Specification
# ============================================================================

@dataclass
class TableSpecification:
    """
    Root table specification document.

    This is the primary artifact generated by Stage 2 (analyzer-tablespec-gen)
    and consumed by Stage 3 (analyzer-crosstabs) for cross-tabulation generation.

    Structure:
        - metadata: Document metadata (spec_id, project_id, dataset_id, description)
        - filter_clause: Data filtering rules (age_min, age_max, exclude_incomplete)
        - weight_indicator: Weight variable name
        - row_indicators: List of row indicator specifications
        - column_indicators: List of column indicator specifications
    """
    # Document metadata
    metadata: Dict[str, str]
    filter_clause: Dict[str, Any] = field(default_factory=dict)
    weight_indicator: Optional[str] = None

    # Indicators (lists of IndicatorSpec)
    row_indicators: List[IndicatorSpec] = field(default_factory=list)
    column_indicators: List[IndicatorSpec] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "metadata": self.metadata,
            "filter_clause": self.filter_clause,
            "weight_indicator": self.weight_indicator,
            "row_indicators": [ind.to_dict() for ind in self.row_indicators],
            "column_indicators": [ind.to_dict() for ind in self.column_indicators]
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TableSpecification":
        """Create instance from dictionary (for loading from JSON)."""
        # Handle row_indicators - support both new (array) and old (dict) formats
        row_indicators_data = data.get("row_indicators", [])
        if isinstance(row_indicators_data, list):
            # New format: array of indicators
            row_indicators = [
                IndicatorSpec.from_dict(ind)
                for ind in row_indicators_data
            ]
        else:
            # Old format: dict with indicator code as key
            row_indicators = [
                IndicatorSpec.from_dict(details, code)
                for code, details in row_indicators_data.items()
            ]

        # Handle column_indicators - support both new (array) and old (dict) formats
        column_indicators_data = data.get("column_indicators", [])
        if isinstance(column_indicators_data, list):
            # New format: array of indicators
            column_indicators = [
                IndicatorSpec.from_dict(ind)
                for ind in column_indicators_data
            ]
        else:
            # Old format: dict with indicator code as key
            column_indicators = [
                IndicatorSpec.from_dict(details, code)
                for code, details in column_indicators_data.items()
            ]

        return cls(
            metadata=data.get("metadata", {}),
            filter_clause=data.get("filter_clause", {}),
            weight_indicator=data.get("weight_indicator"),
            row_indicators=row_indicators,
            column_indicators=column_indicators
        )

    def get_indicator_by_code(self, code: str) -> Optional[IndicatorSpec]:
        """Find an indicator by its code."""
        for ind in self.row_indicators:
            if ind.indicator_code == code:
                return ind
        for ind in self.column_indicators:
            if ind.indicator_code == code:
                return ind
        return None

    def validate(self) -> List[str]:
        """
        Validate the table specification structure.

        Returns:
            List of error messages (empty if valid).
        """
        errors = []

        # Check metadata
        required_metadata = ["spec_id", "project_id"]
        for field in required_metadata:
            if field not in self.metadata:
                errors.append(f"Missing required metadata field: '{field}'")

        # Check indicators exist
        if not self.row_indicators:
            errors.append("No row_indicators defined")

        if not self.column_indicators:
            errors.append("No column_indicators defined")

        # Validate each indicator (row)
        for i, indicator in enumerate(self.row_indicators):
            code = indicator.indicator_code or f"index_{i}"
            if not indicator.indicator_label:
                errors.append(f"row_indicators[{i}] ({code}): missing indicator_label")
            if not indicator.base_variables:
                errors.append(f"row_indicators[{i}] ({code}): no base_variables defined")
            if not indicator.tabulation_type:
                errors.append(f"row_indicators[{i}] ({code}): missing tabulation_type")
            if not indicator.tabulation_metric:
                errors.append(f"row_indicators[{i}] ({code}): missing tabulation_metric")

        # Validate each indicator (column)
        for i, indicator in enumerate(self.column_indicators):
            code = indicator.indicator_code or f"index_{i}"
            if not indicator.indicator_label:
                errors.append(f"column_indicators[{i}] ({code}): missing indicator_label")
            if not indicator.base_variables:
                errors.append(f"column_indicators[{i}] ({code}): no base_variables defined")
            if not indicator.tabulation_type:
                errors.append(f"column_indicators[{i}] ({code}): missing tabulation_type")
            if not indicator.tabulation_metric:
                errors.append(f"column_indicators[{i}] ({code}): missing tabulation_metric")

        return errors


# ============================================================================
# Convenience Functions
# ============================================================================

def create_empty_spec(
    spec_id: str = "new_spec",
    project_id: str = "default_project",
    dataset_id: str = "default_dataset",
    **kwargs
) -> TableSpecification:
    """Create an empty table specification document.

    Args:
        spec_id: Specification ID
        project_id: Project ID
        dataset_id: Dataset ID
        **kwargs: Additional metadata fields (e.g., source_file for backward compatibility)

    Returns:
        Empty TableSpecification instance
    """
    metadata = {
        "spec_id": spec_id,
        "project_id": project_id,
        "dataset_id": dataset_id,
        "description": "Table specification"
    }
    # Add any extra kwargs to metadata (for backward compatibility)
    metadata.update(kwargs)

    return TableSpecification(
        metadata=metadata,
        filter_clause={},
        row_indicators=[],
        column_indicators=[]
    )


def load_from_file(filepath: str) -> TableSpecification:
    """Load table specification from JSONC file."""
    import json
    with open(filepath, 'r') as f:
        data = json.load(f)
    return TableSpecification.from_dict(data)


def save_to_file(spec: TableSpecification, filepath: str):
    """Save table specification to JSONC file."""
    import json
    with open(filepath, 'w') as f:
        json.dump(spec.to_dict(), f, indent=2)


# ============================================================================
# Legacy Support (for backward compatibility during transition)
# ============================================================================

# Legacy class names mapped to new structure
LEGACY_FIELD_MAP = {
    # Old -> New
    'statistic_type': 'tabulation_statistics.type',
    'source_variables': 'base_variables',
    'transformation_rules': 'base_variables[].generation',
    'target_variables': 'base_variables',
    'target_values': 'base_variables[].values',
    'question_label': 'indicator_label',
    'related_question': 'questionnaire_questions',
    'tabulation': 'tabulation_statistics'
}


def migrate_legacy_spec(legacy_data: Dict[str, Any]) -> TableSpecification:
    """
    Migrate legacy table specification format to new format.

    This helper function converts data using old field names to the new structure.
    """
    # Implementation would go here if needed for transition period
    pass
